[package]
name = "fastcdc-hs-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
fastcdc = "3.1.0"
hs-bindgen = { version = "0.9.0", features = ["full"] }

[patch.crates-io]
hs-bindgen-types = { path = "../hs-bindgen-types" }
